### ISSUE TITLE
Use custom status to post in Meeting and also set a time to the status update

### ISSUE THREAD

**Issue by ByteMoT** [mattermost/mattermost-plugin-mscalendar#341] opened 2023-10-19 20:56 UTC
Allow the Plugin to use the Custom status and make a meeting with a time from the calendar as the time limit

Having this directly blocking out your time will help with showing availability, having the option to still use away and DND would be good also but having it reflect in the status would be amazing

![image](https://github.com/mattermost/mattermost-plugin-mscalendar/assets/145804837/08011791-5be6-4932-92ca-a93db2c1f67b)

**Comment by mickmister** [comment] 2023-10-20 15:33
Hi @ByteMoT, thanks for filing this issue. This is a missing feature we do intend to implement. There is an existing issue to discuss this further https://github.com/mattermost/mattermost-plugin-mscalendar/issues/228. Please add any comments you may have on that issue. Do you mind if I close this as it seems to be a duplicate of the linked issue?

**Closed** 2023-10-20 16:40 UTC
