### ISSUE TITLE
Intermittent panic error when using subscribe 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-mscalendar#116] opened 2020-05-06 05:44 UTC
I don't have repro steps but occasionally I see the subscribe command fail. 
The log shows the following (more logs available from this occurrence):
```
{"level":"debug","ts":1588742648.462739,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_typing"}
{"level":"debug","ts":1588742648.492857,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/commands/execute","request_id":"p8wybkdr9tftpn3earnnsujbfy"}
{"level":"debug","ts":1588742649.285857,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.285922,"caller":"plugin/hclog_adapter.go:53","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1908695]","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.285938,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.285951,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 82 [running]:","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.285971,"caller":"plugin/hclog_adapter.go:53","msg":"github.com/mattermost/mattermost-plugin-mscalendar/server/remote/msgraph.(*impl).HandleWebhook(0xc00040a9c0, 0x1dcdbc0, 0xc0003e7520, 0xc0004b6800, 0x15f17a5, 0x1c11fe0, 0xc0002ac300)","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.2859871,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-mscalendar/server/remote/msgraph/handle_webhook.go:37 +0x1f5","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.285999,"caller":"plugin/hclog_adapter.go:53","msg":"github.com/mattermost/mattermost-plugin-mscalendar/server/api.(*api).notification(0xc00040af60, 0x1dcdbc0, 0xc0003e7520, 0xc0004b6800)","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1588742649.2860138,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-mscalendar/server/api/notification.go:14 +0x5a","plugin_id":"com.mattermost.mscalendar"}
```
I have no repro steps. There are some details I've noticed:
- I've only seen this occur with 1 user ``MIchael3`
- Restarting the plugin resolves the issue

**Comment by mickmister** [comment] 2020-05-19 15:51
Conversation about this https://community-daily.mattermost.com/core/pl/9hx8mz6n3fg5xkfikqtx3q1nea

**Comment by mickmister** [comment] 2020-05-19 15:53
Closing due to non-reproducibility

**Closed by mickmister** 2020-05-19 15:53 UTC
Labels: Type/Bug

**Comment by mickmister** [comment] 2020-05-26 23:02
@levb This error is occurring again where it seems the `Logger` attached to `remote.Client` is nil. This time it is happening on user disconnect, rather than subscribe. Here's the context: https://github.com/mattermost/mattermost-plugin-mscalendar/pull/141#issuecomment-634202225
